{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "536b590c_0247fafa",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 19
      },
      "lineNbr": 0,
      "author": {
        "id": 1000520
      },
      "writtenOn": "2022-02-14T21:28:36Z",
      "side": 1,
      "message": "Looks like the test cases are failing now, unfortunately.\n",
      "revId": "4fc5bb67b2d8908024aba55c432a24b424493a55",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}